INSERT INTO cartes (id, nom, rarete, description, image_url) VALUES
(1, 'Teckel électricien', 1, 'Teckel avec des compétences en électricité', './img_Cartes/Teckel-0-01.webp'),
(2, 'Teckel plombier', 1, 'Teckel spécialisé en plomberie', './img_Cartes/Teckel-0-02.webp'),
(3, 'Teckel mécanicien', 1, 'Teckel expert en mécanique', './img_Cartes/Teckel-0-03.webp'),
(4, 'Teckel boulanger', 1, 'Teckel qui aime faire du pain', './img_Cartes/Teckel-0-04.webp'),
(5, 'Teckel pâtissier', 1, 'Teckel talentueux en pâtisserie', './img_Cartes/Teckel-0-05.webp'),
(6, 'Teckel comptable', 1, 'Teckel excellent avec les chiffres', './img_Cartes/Teckel-0-06.webp'),
(7, 'Teckel banquier', 1, 'Teckel avec une expertise bancaire', './img_Cartes/Teckel-0-07.webp'),
(8, 'Teckel bibliothécaire', 1, 'Teckel passionné par les livres', './img_Cartes/Teckel-0-08.webp'),
(9, 'Teckel jardinier', 1, 'Teckel qui aime entretenir les jardins', './img_Cartes/Teckel-0-09.webp'),
(10, 'Teckel agriculteur', 1, 'Teckel qui cultive la terre', './img_Cartes/Teckel-0-10.webp'),
(11, 'Teckel fermier', 1, 'Teckel travaillant dans une ferme', './img_Cartes/Teckel-0-11.webp'),
(12, 'Teckel pêcheur', 1, 'Teckel habile à attraper des poissons', './img_Cartes/Teckel-0-12.webp'),
(13, 'Teckel forgeron', 1, 'Teckel expert en forge', './img_Cartes/Teckel-0-13.webp'),
(14, 'Teckel charpentier', 1, 'Teckel compétent en charpenterie', './img_Cartes/Teckel-0-14.webp'),
(15, 'Teckel maçon', 1, 'Teckel bâtisseur', './img_Cartes/Teckel-0-15.webp'),
(16, 'Teckel ébéniste', 1, 'Teckel travailleur du bois', './img_Cartes/Teckel-0-16.webp'),
(17, 'Teckel coiffeur', 1, 'Teckel styliste pour poils', './img_Cartes/Teckel-0-17.webp'),
(18, 'Teckel magicien', 1, 'Teckel aux talents magiques', './img_Cartes/Teckel-0-18.webp'),
(19, 'Teckel réceptionniste', 1, 'Teckel expert en accueil', './img_Cartes/Teckel-0-19.webp'),
(20, 'Teckel secrétaire', 1, 'Teckel qui gère les documents', './img_Cartes/Teckel-0-20.webp'),
(21, 'Teckel étudiant', 1, 'Teckel en pleine formation', './img_Cartes/Teckel-0-21.webp'),
(22, 'Teckel coach sportif', 1, 'Teckel qui motive les autres', './img_Cartes/Teckel-0-22.webp'),
(23, 'Teckel esthéticien', 1, 'Teckel spécialiste en beauté', './img_Cartes/Teckel-0-23.webp'),
(24, 'Teckel concierge', 1, 'Teckel toujours au service', './img_Cartes/Teckel-0-24.webp'),
(25, 'Teckel barman', 1, 'Teckel qui prépare les boissons', './img_Cartes/Teckel-0-25.webp'),
(26, 'Teckel barista', 1, 'Teckel spécialiste des cafés', './img_Cartes/Teckel-0-26.webp'),
(27, 'Teckel chocolatier', 1, 'Teckel expert en chocolat', './img_Cartes/Teckel-0-27.webp'),
(28, 'Teckel fleuriste', 1, 'Teckel amoureux des fleurs', './img_Cartes/Teckel-0-28.webp'),
(29, 'Teckel sculpteur', 1, 'Teckel artiste talentueux', './img_Cartes/Teckel-0-29.webp'),
(30, 'Teckel photographe', 1, 'Teckel capturant des moments', './img_Cartes/Teckel-0-30.webp'),
(31, 'Teckel peintre', 1, 'Teckel passionné par l''art', './img_Cartes/Teckel-0-31.webp'),
(32, 'Teckel écrivain', 1, 'Teckel maître des mots', './img_Cartes/Teckel-0-32.webp'),
(33, 'Teckel journaliste', 1, 'Teckel informateur', './img_Cartes/Teckel-0-33.webp'),
(34, 'Teckel linguiste', 1, 'Teckel expert en langues', './img_Cartes/Teckel-0-34.webp'),
(35, 'Teckel interprète', 1, 'Teckel facilitant la communication', './img_Cartes/Teckel-0-35.webp'),
(36, 'Teckel traducteur', 1, 'Teckel maître des traductions', './img_Cartes/Teckel-0-36.webp'),
(37, 'Teckel guide touristique', 1, 'Teckel explorateur', './img_Cartes/Teckel-0-37.webp'),
(38, 'Teckel mannequin', 1, 'Teckel élégant', './img_Cartes/Teckel-0-38.webp'),
(39, 'Teckel danseur', 1, 'Teckel qui bouge avec style', './img_Cartes/Teckel-0-39.webp'),
(40, 'Teckel DJ', 1, 'Teckel maître du mix', './img_Cartes/Teckel-0-40.webp'),
(41, 'Teckel acteur', 1, 'Teckel qui brille sur scène', './img_Cartes/Teckel-0-41.webp'),
(42, 'Teckel chanteur', 1, 'Teckel à la belle voix', './img_Cartes/Teckel-0-42.webp'),
(43, 'Teckel réalisateur', 1, 'Teckel derrière la caméra', './img_Cartes/Teckel-0-43.webp'),
(44, 'Teckel couturier', 1, 'Teckel créateur de mode', './img_Cartes/Teckel-0-44.webp'),
(45, 'Teckel styliste', 1, 'Teckel spécialiste des looks', './img_Cartes/Teckel-0-45.webp'),
(46, 'Teckel bijoutier', 1, 'Teckel créateur de bijoux', './img_Cartes/Teckel-0-46.webp'),
(47, 'Teckel agent immobilier', 1, 'Teckel expert en biens', './img_Cartes/Teckel-0-47.webp'),
(48, 'Teckel pharmacien', 1, 'Teckel dans la santé', './img_Cartes/Teckel-0-48.webp'),
(49, 'Teckel dentiste', 1, 'Teckel qui soigne les dents', './img_Cartes/Teckel-0-49.webp'),
(50, 'Teckel vétérinaire', 1, 'Teckel au service des animaux', './img_Cartes/Teckel-0-50.webp'),
(51, 'Teckel médecin', 2, 'Teckel qui soigne les humains', './img_Cartes/Teckel-0-51.webp'),
(52, 'Teckel professeur', 2, 'Teckel qui enseigne', './img_Cartes/Teckel-0-52.webp'),
(53, 'Teckel psychanalyste', 2, 'Teckel à l''écoute', './img_Cartes/Teckel-0-53.webp'),
(54, 'Teckel psychologue', 2, 'Teckel qui analyse les émotions', './img_Cartes/Teckel-0-54.webp'),
(55, 'Teckel militaire', 2, 'Teckel courageux', './img_Cartes/Teckel-0-55.webp'),
(56, 'Teckel pilote', 2, 'Teckel au commande d''un avion', './img_Cartes/Teckel-0-56.webp'),
(57, 'Teckel capitaine de bateau', 2, 'Teckel des mers', './img_Cartes/Teckel-0-57.webp'),
(58, 'Teckel météorologue', 2, 'Teckel qui analyse la météo', './img_Cartes/Teckel-0-58.webp'),
(59, 'Teckel historien', 2, 'Teckel passionné par l''histoire', './img_Cartes/Teckel-0-59.webp'),
(60, 'Teckel archéologue', 2, 'Teckel explorateur du passé', './img_Cartes/Teckel-0-60.webp'),
(61, 'Teckel anthropologue', 2, 'Teckel qui étudie les sociétés', './img_Cartes/Teckel-0-61.webp'),
(62, 'Teckel sociologue', 2, 'Teckel observateur des relations humaines', './img_Cartes/Teckel-0-62.webp'),
(63, 'Teckel policier', 2, 'Teckel gardien de l''ordre', './img_Cartes/Teckel-0-63.webp'),
(64, 'Teckel enquêteur', 2, 'Teckel résolvant des mystères', './img_Cartes/Teckel-0-64.webp'),
(65, 'Teckel agent de sécurité', 2, 'Teckel protégeant les biens et les personnes', './img_Cartes/Teckel-0-65.webp'),
(66, 'Teckel guide de montagne', 2, 'Teckel des sommets', './img_Cartes/Teckel-0-66.webp'),
(67, 'Teckel maître d''hôtel', 2, 'Teckel au service des clients', './img_Cartes/Teckel-0-67.webp'),
(68, 'Teckel entraîneur', 2, 'Teckel qui motive et accompagne', './img_Cartes/Teckel-0-68.webp'),
(69, 'Teckel géologue', 2, 'Teckel explorant la Terre', './img_Cartes/Teckel-0-69.webp'),
(70, 'Teckel botaniste', 2, 'Teckel expert des plantes', './img_Cartes/Teckel-0-70.webp'),
(71, 'Teckel zoologiste', 2, 'Teckel passionné par les animaux', './img_Cartes/Teckel-0-71.webp'),
(72, 'Teckel retraité', 2, 'Teckel profitant de la vie', './img_Cartes/Teckel-0-72.webp'),
(73, 'Teckel architecte', 3, 'Teckel bâtisseur de rêves', './img_Cartes/Teckel-0-73.webp'),
(74, 'Teckel économiste', 3, 'Teckel en gestion financière', './img_Cartes/Teckel-0-74.webp'),
(75, 'Teckel mathématicien', 3, 'Teckel expert en mathématiques', './img_Cartes/Teckel-0-75.webp'),
(76, 'Teckel ingénieur', 3, 'Teckel inventeur talentueux', './img_Cartes/Teckel-0-76.webp'),
(77, 'Teckel statisticien', 3, 'Teckel maître des chiffres', './img_Cartes/Teckel-0-77.webp'),
(78, 'Teckel philosophe', 3, 'Teckel penseur réfléchi', './img_Cartes/Teckel-0-78.webp'),
(79, 'Teckel diplomate', 3, 'Teckel représentant son pays', './img_Cartes/Teckel-0-79.webp'),
(80, 'Teckel linguiste', 3, 'Teckel expert en langues', './img_Cartes/Teckel-0-80.webp'),
(81, 'Teckel juge', 3, 'Teckel qui rend la justice', './img_Cartes/Teckel-0-81.webp'),
(82, 'Teckel procureur', 3, 'Teckel défenseur des lois', './img_Cartes/Teckel-0-82.webp'),
(83, 'Teckel contrôleur aérien', 3, 'Teckel guidant les avions', './img_Cartes/Teckel-0-83.webp'),
(84, 'Teckel parfumeur', 3, 'Teckel créateur de fragrances', './img_Cartes/Teckel-0-84.webp'),
(85, 'Teckel ostéopathe', 3, 'Teckel guérissant les douleurs', './img_Cartes/Teckel-0-85.webp'),
(86, 'Teckel avocat', 4, 'Teckel expert en droit', './img_Cartes/Teckel-0-86.webp'),
(87, 'Teckel détective privé', 4, 'Teckel résolvant des affaires complexes', './img_Cartes/Teckel-0-87.webp'),
(88, 'Teckel astrophysicien', 4, 'Teckel explorateur des étoiles', './img_Cartes/Teckel-0-88.webp'),
(89, 'Teckel magistrat', 4, 'Teckel garant de la loi', './img_Cartes/Teckel-0-89.webp'),
(90, 'Teckel bijoutier', 4, 'Teckel créateur de pièces uniques', './img_Cartes/Teckel-0-90.webp'),
(91, 'Teckel chocolatier', 4, 'Teckel maître du chocolat', './img_Cartes/Teckel-0-91.webp'),
(92, 'Teckel écrivain renommé', 4, 'Teckel célèbre pour ses écrits', './img_Cartes/Teckel-0-92.webp'),
(93, 'Teckel chef cuisinier étoilé', 4, 'Teckel étoile de la gastronomie', './img_Cartes/Teckel-0-93.webp'),
(94, 'Teckel chef cuisinier', 5, 'Teckel maître des saveurs', './img_Cartes/Teckel-0-94.webp'),
(95, 'Teckel sommelier', 5, 'Teckel expert en vins et spiritueux', './img_Cartes/Teckel-0-95.webp'),
(96, 'Teckel maître d''hôtel de prestige', 5, 'Teckel au service des plus grands', './img_Cartes/Teckel-0-96.webp'),
(97, 'Teckel magistrat', 5, 'Teckel garant des lois', './img_Cartes/Teckel-0-97.webp'),
(98, 'Teckel roi', 6, 'Teckel majestueux', './img_Cartes/Teckel-0-98.webp'),
(99, 'Teckel astronaute', 6, 'Teckel explorateur de l''espace', './img_Cartes/Teckel-0-99.webp'),
(100, 'Teckel pilote de F1', 6, 'Teckel à toute vitesse', './img_Cartes/Teckel-0-100.webp')
ON CONFLICT (id) DO NOTHING;
